api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    #show_webby: false

    formats:
        jsonld:   ['application/ld+json']
        html:     ['text/html']
        jsondatatables:   ['application/datatables+json']

    enable_swagger_ui: true