api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    #show_webby: false

    formats:
        #jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
        jsondt:   ['application/dt+json'] #format for datatables.js

    collection:
        pagination:
            enabled: false