security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        login:
            entity:
                class: App\Entity\User
                property: id
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory: { memory: ~ }

    firewalls:
        login:
            pattern: ^/api/login
            context: main
            guard:
                provider: login
                authenticators:
                    - App\Security\LoginAuthenticator
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true
                user_provider: login

        main:
            pattern: ^/
            #stateless: true
            #context: main
            form_login:
                always_use_default_target_path: true
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                user_provider: fos_userbundle

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            #context: main
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin(/|$), role: ROLE_ADMIN }
        - { path: ^/(account|teacher|student|child)/, role: IS_AUTHENTICATED_REMEMBERED}