services:
    _defaults:
        public: true

    fos_user.mailer:
        class: 'App\Tests\Functional\Security\Mailer'
        arguments:
            - '@mailer'
            - '@router'
            - '@templating'
            -
                confirmation.template: '%fos_user.registration.confirmation.template%'
                from_email: {confirmation: ''}