AppBundle\Entity\Examples:
    type: entity
    table: examples
    repositoryClass: AppBundle\Repository\ExamplesRepository
    indexes:
        try_id:
            columns:
                - try_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        addTime:
            type: datetime
            nullable: false
            column: add_time
        first:
            type: float
            nullable: false
            precision: 10
            scale: 0
        sign:
            type: integer
            nullable: false
            options:
                unsigned: false
        second:
            type: float
            nullable: false
            precision: 10
            scale: 0
        answer:
            type: float
            nullable: true
            precision: 10
            scale: 0
        isRight:
            type: boolean
            nullable: true
            column: is_right
    manyToOne:
        try:
            targetEntity: Tries
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                try_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
