AppBundle\Entity\Sessions:
    type: entity
    table: sessions
    repositoryClass: AppBundle\Repository\SessionsRepository
    indexes:
        user_id:
            columns:
                - user_id
    uniqueConstraints:
        sid:
            columns:
                - sid
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lastVisitTime:
            type: datetime
            nullable: false
            column: last_visit_time
        sid:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
