AppBundle\Entity\Tries:
    type: entity
    repositoryClass: AppBundle\Repository\TriesRepository
    table: tries
    indexes:
        IDX_9DC696CE613FECDF:
            columns:
                - session_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        startTime:
            type: datetime
            nullable: false
            column: start_time
        settings:
            type: object
            nullable: false
            length: null
            options:
                fixed: false
    manyToOne:
        session:
            targetEntity: Sessions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                session_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
